### ISSUE TITLE
Erster Entwurf der Einzelansicht von Textträgern

### ISSUE THREAD

**Issue by olvidalo** [cceh/papyri#27]
* Textträgerdaten über die Textansicht

Noch zu ergänzen:

* Inhaltsangabe der Texte (tei:content)
* Freitextdaten bei Feldern wie Sprache, Datierung usw.
* Transkriptionen (tei:text)

**Comment by araborn** [comment]
- Inhaltsangabe eingebaut
- Design geändert
- Freitextdaten?
- Transkription 
-- Wie sollen die Daten aufbereitet werden
