### ISSUE TITLE
Benutzerverwaltung

### ISSUE THREAD

**Issue by olvidalo** [cceh/papyri#30]
In modules/auth.xqm gibt es bereits einen Ansatz zum Login. Diesen bitte ein bisschen erweitern:

* statt auth:logged-in soll es auth:get-user geben, die bei eingeloggtem User den Benutzernamen und bei einem Gast () zurückgibt
* Benutzerrollen
 * jedem Benutzer soll eine Rolle zugeordnet werden können, zunächst mal "user", "editor" und "admin"
 * eine Funktion auth:get-role soll bei angemeldetem Benutzer dessen Rolle, ansonsten "guest" zurückgeben

* Das Login-Formular in der Menüleiste zum Funktionieren bringen
* Aktuellen Benutzernamen in der Menüleiste anzeigen

**Comment by PatrickSahle** [comment]
total unnötig von mir zu erwähnen, dass damals Jonathan das login für 
Totenbuch gemacht hatte und deshalb zu interviewen ist, wie man es heute 
wohl anders machen würde

p

Am 24.08.2015 um 12:17 schrieb Marcel Schaeben:
>
> In modules/auth.xqm gibt es bereits einen Ansatz zum Login. Diesen 
> bitte ein bisschen erweitern:
>
>   * statt auth:logged-in soll es auth:get-user geben, die bei
>     eingeloggtem User den Benutzernamen und bei einem Gast () zurückgibt
>  *
>
>     Benutzerrollen
>
>       o jedem Benutzer soll eine Rolle zugeordnet werden können,
>         zunächst mal "user", "editor" und "admin"
>       o eine Funktion auth:get-role soll bei angemeldetem Benutzer
>         dessen Rolle, ansonsten "guest" zurückgeben
>  *
>
>     Das Login-Formular in der Menüleiste zum Funktionieren bringen
>
>   * Aktuellen Benutzernamen in der Menüleiste anzeigen
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cceh/papyri/issues/30>.
>


-- 
------------------------------------------------------------------------
Cologne Center for eHumanities (CCeH) <http://www.cceh.uni-koeln.de/> 
(Geschäftsführung; Projekte der Akademie der Wissenschaften NRW)
Data Center for the Humanities <http://www.dch.uni-koeln.de/> (Koordination)
DiXiT ITN <http://www.dixit.uni-koeln.de/> (Fellow Supervisor)
Institut für Dokumentologie und Editorik <http://www.i-d-e.de> (Mitglied)


Postanschrift: Cologne Center for eHumanities (CCeH), Universität zu 
Köln, Albertus-Magnus-Platz, D-50923 Köln
Büro: Universitätsstr. 22, Dachgeschoss rechts
Telefon: +49 - (0)221 - 470 3894
