### ISSUE TITLE
Startseitenslideshowverschönerungsaktion

### ISSUE THREAD

**Issue by PatrickSahle** [cceh/papyri#34]
Ich hatte dazu im Juni (?) ein mail geschrieben:
Frage, ob wir nochmal über die Präsentation der einzelnen Slides in der Startseitenslideshow nachdenken wollen. Ich finde, man könnte das noch ein wenig "einladender" und die Unterschiede zwischen den beiden Sichten klarer machen, indem man auf die gefelderte Darstellung verzichtet und es stärker narrativ macht. Beispiel, erstes Bild bei "Sammlung" (was meiner Meinung nach "Sammlung / Objekte" heißen sollte), da würde ich sagen: "Stück Leinen unbekannter Herkunft, 3. bis 4. Jahrhundert, Inventarnummer 05512, mit Teil eines Liebeszaubers beschrieben" - oder so ähnlich.
Ebenso bei "Texte", erstes Beispiel: "Christlicher Brief, publiziert in ...[ausführlicher]..., auf einem Papyrus des 5. bis 6. Jahrhunderts unbekannter Herkunft."

... von mir aus kann man hart codierte Textsnippets irgendwo hinterlegen. Frage: wie fügt sich das in die Gesamtarchitektur ein?

**Comment by olvidalo** [comment]
Wir müssen erst mal sehen ob das mit den zwei verschiedenen Ansichten überhaupt sinnvoll ist. Die Papyrologen haben ja im letzten Treffen gesagt dass nur Textträger relevant sind, nicht die einzelnen Texte.

**Comment by PatrickSahle** [comment]
Mir ist wichtig, dass wir eine funktionale, strukturelle und dann auch visuelle Metapher dafür finden, dass wir es hier mit zwei grundsätzlich verschiedenen Arten von Dingen zu tun haben: Mit materiellen Objekten einerseits (die als Objekte beschrieben und durch ein Foto repräsentiert werden) und mit ideellen/abstrakten Dingen (texten) Andererseits, die über ihren Titel beschreiben und als Text/Transkription repräsentiert werden.
Ich halte die Doppelgalerie für gut geeignet, diese Botschaft zu kommunizieren und zugleich eine explorativem immersive Benutzungssituation zu erzeugen.
Ich bin aber für neue Vorschläge ganz offen.

**Comment by olvidalo** [comment]
This issue was moved to SebastianZimmer/papyri#1
