### ISSUE TITLE
Reporting-Seite anlegen

### ISSUE THREAD

**Issue by PatrickSahle** [cceh/papyri#35]
Ziel: Aufbau einer Reporting-Seite zum Inhalt und Zustand der Datenbank
Vorgehen: Query schreiben, das entsprechende Dinge abfragt und als Ergebnisseite ausliefert
Beispiel 1: Objekte / XML-Dateien, die kein idno/Inventarnummer haben
Beispiel 2: note type="Zeitpunkt" mit @notBefore als Fehler melden
Beispiel 3: [wenn wir die Datumsangaben sprechend in note ergänzen] - welche Objekte haben zwar eine scharfe (@notBefore, @notAfter, @when) aber keine sprechende (note) Angabe?

**Comment by hennyu** [comment]
zu 2 ergänzend: note type="Zeitraum" mit @when als Fehler melden

**Comment by olvidalo** [comment]
/apps/papyri/report
