### ISSUE TITLE
Mehrfache Ausgabe von "Papyrus" bei Übersichten

### ISSUE THREAD

**Issue by PatrickSahle** [cceh/papyri#36]
bei http://papyri.uni-koeln.de:8080/apps/papyri/uebersicht und anderen Übersichtsseiten wird Papyrus dreimal angezeigt

**Comment by olvidalo** [comment]
Das liegt daran, dass in den Daten drei mal Papyrus mit unterschiedlicher Anzahl von Leerzeichen dahinter in der Datenbank steht. Ich will hier nicht normalize-space benutzen weil wir das in der Datenbank korrigieren sollten...

**Comment by PatrickSahle** [comment]
Am 31.08.2015 um 16:00 schrieb Marcel Schaeben:
>
> Das liegt daran, dass in den Daten drei mal Papyrus mit 
> unterschiedlicher Anzahl von Leerzeichen dahinter in der Datenbank 
> steht. Ich will hier nicht normalize-space benutzen weil wir das in 
> der Datenbank korrigieren sollten...
>
da hast Du vollkommen recht
Frage: wer macht systematische Änderungen im Datenbestand? Du oder 
jemand anders?
Andere Frage: haben wir eine Werteliste für Material schon im XML-Schema?
     - das sollten wir
     - Anschlussfrage: wer pflegt das Schema?

Grüße, Patrick
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cceh/papyri/issues/36#issuecomment-136379328>.
>


-- 
------------------------------------------------------------------------
Cologne Center for eHumanities (CCeH) <http://www.cceh.uni-koeln.de/> 
(Geschäftsführung; Projekte der Akademie der Wissenschaften NRW)
Data Center for the Humanities <http://www.dch.uni-koeln.de/> (Koordination)
DiXiT ITN <http://www.dixit.uni-koeln.de/> (Fellow Supervisor)
Institut für Dokumentologie und Editorik <http://www.i-d-e.de> (Mitglied)


Postanschrift: Cologne Center for eHumanities (CCeH), Universität zu 
Köln, Albertus-Magnus-Platz, D-50923 Köln
Büro: Universitätsstr. 22, Dachgeschoss rechts
Telefon: +49 - (0)221 - 470 3894

**Comment by hennyu** [comment]
bisher war das ich (systematische Änderungen), Marcel, übernimmst Du? Werteliste für Material gibt es im Schema. Die Schemadateien sind Bestandteil der oXygen-Arbeitsumgebung (epidoc_c). Das Schema wäre über Roma zu pflegen (ODD-Datei). Das kann es, wenn man mit RelaxNG die Inhalte von Elementen beschreiben möchte, zu Namensraumproblemen kommen, wenn das Schema über Roma exportiert wird (statt TEI-Namensraum wird manchmal ein leerer Namensraum generiert). Das müsste dann händisch nachkorrigiert werden (in der ODD-Datei und der exportieren RelaxNG-Datei). Oder man ändert die ODD/RelaxNG-Datei direkt an den entsprechenden Stellen, wenn es nur um die Anpassung von Wertelisten geht. Bei Fragen fragt ihr hier oder per Mail, ja?

**Comment by PatrickSahle** [comment]
issue ist durch das Aufräumen der Daten erledigt
